name: connectivity_info
description: Connectivity Info.
version: 0.0.1

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  internet_connection_checker_plus: ^1.0.1
  mockito: ^5.4.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter: null
